[project]
authors = [{name = "Bror Jönsson", email = "brorfred@gmail.com"}]
dependencies = ["haversine>=2.9.0,<3", "projmap>=2.0.5,<3"]
name = "abstemp"
requires-python = ">= 3.11"
version = "0.1.0"

[dependency-groups]
dev = ["ipython>=9.10.0,<10"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tool.pixi.pypi-dependencies]
abstemp = { path = ".", editable = true }
#projmap = { path = "/home/bror/code/projmap", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
numpy = ">=2.4.2,<3"
scipy = ">=1.17.0,<2"
matplotlib = ">=3.10.8,<4"
pandas = ">=3.0.0,<4"
xarray = ">=2026.1.0,<2027"
ipython = ">=9.10.0,<10"
cmap = ">=0.7.1,<0.8"
cdsapi = ">=0.7.7,<0.8"
netcdf4 = ">=1.7.4,<2"
dask = ">=2026.1.2,<2027"
distributed = ">=2026.1.2,<2027"
line_profiler = ">=5.0.1,<6"
pydap = ">=3.5.8,<4"
parquet-python = ">=1.3.1,<2"
plotly = ">=6.6.0,<7"
seaborn = ">=0.13.2,<0.14"
cartopy = ">=0.24"
pyresample = ">=1.26"
scikit-learn = ">=1.4"
dynaconf = ">=3.2"
copernicusmarine = ">=2.4.1,<3"
